server:
  listen: 8080 # Port for the reverse proxy to listen.
  workers: 4

  upstreams: # All Servers are upstreams
    - id: node1
      url: localhost:8001
    - id: node2
      url: localhost:8002

  headers:
    - key: x-forward-for
      value: '$ip'

    - key: Authorization
      value: 'Bearer xyz'
  
  rules:
    - path: /
      upstream: 
        - node1
        - node2

    - path: /admin
      upstream: 
        - node2